version: '3.8'

services:
  db:
    #имя контейнера
    container_name: 'db'
    #версия образа для скачивания
    image: postgres:14.1-alpine
    restart: always
    #переменные окружения
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      #слева порт ОС, справа порт контейнера
      - "5434:5432"  
    networks:
      - custom
#сеть и драйвер
networks:
  custom:
    driver: bridge
